### ISSUE TITLE
Create shooter controller

### ISSUE THREAD

**Issue by james-ward** [thedropbears/pycubehammer#5]
Orchestrate the turret, inclination, shooter and intake.

States:
* Intaking
* tracking
* Shooting

```[tasklist]
### Tasks
- [x] Add the skeleton shoot controller
- [ ] Implement the default idle state
- [ ] Implement the intaking state
- [ ] Implement the tracking state
- [ ] Implement the shooting state
```
